INSERT INTO privileges (name, description,screen_key)
VALUES
    ('PRIVILEGE_INGESTION_SOURCE_CONNECT_OVERVIEW','Ingestion - Source connection - Overview','source_connection'),
    ('PRIVILEGE_INGESTION_SOURCE_CONNECT_CONNECT','Ingestion - Source connection - Add new connect','source_connection'),
    ('PRIVILEGE_ANALYTIC_BI_GENERAL_INFORMATION_OVERVIEW','Analytics and BI - General information - Overview','general_information'),
    ('PRIVILEGE_ANALYTIC_BI_GENERAL_INFORMATION_EDIT_DASHBOARD','Analytics and BI - General information - Edit dashboard','general_information'),
    ('PRIVILEGE_ANALYTIC_BI_TRACKING_BEHAVIOR_CUSTOMER_BEHAVIOR_OVERVIEW','Analytics and BI - Tracking behavior - Overview of Customer behavior','tracking_behavior'),
    ('PRIVILEGE_ANALYTIC_BI_TRACKING_BEHAVIOR_SEARCH_ENGINE_CUSTOMER_SERVICE_OVERVIEW','Analytics and BI - Customer behavior - Overview of Search engine and Customer service','tracking_behavior'),
    ('PRIVILEGE_ANALYTIC_BI_MARKETING_REPORT_OVERVIEW','Analytics and BI - Marketing report - Overview','marketing_report'),
    ('PRIVILEGE_CUSTOMER_PROFILE_MANAGE_CUSTOMER_OVERVIEW','Customer Profile - Manage customer - Overview','manage_customer'),
    ('PRIVILEGE_CUSTOMER_PROFILE_CUSTOMER_PROFILE_OVERVIEW','Customer Profile - Customer Profile - Overview','customer_profile'),
    ('PRIVILEGE_CUSTOMER_PROFILE_CUSTOMER_PROFILE_EDIT','Customer Profile - Customer Profile - Edit profile','customer_profile'),
    ('PRIVILEGE_CUSTOMER_PROFILE_CUSTOMER_PROFILE_REMOVE','Customer Profile - Customer Profile - Remove profile','customer_profile'),
    ('PRIVILEGE_MARKETING_HUB_CAMPAIGN_OVERVIEW','Marketing hub - Overview campaign','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_CAMPAIGN_CREATE','Marketing hub - Campaign create','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_CAMPAIGN_EDIT','Marketing hub - Campaign edit','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_CAMPAIGN_REMOVE','Marketing hub - Campaign remove','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_DELIVERY_CREATE','Marketing hub - Delivery create','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_DELIVERY_EDIT','Marketing hub - Delivery edit','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_DELIVERY_REMOVE','Marketing hub - Delivery remove','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_CAMPAIGN_DELIVERY_CREATE','Marketing hub - Campaign and Delivery evaluation - Create new report','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_KNOWLEDGE_SHARING_ADD','Marketing hub - Knowledge sharing - Add','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_KNOWLEDGE_SHARING_REMOVE','Marketing hub - Knowledge sharing - Remove','marketing_hub'),
    ('PRIVILEGE_MARKETING_HUB_KNOWLEDGE_SHARING_ASSIGN','Marketing hub - Knowledge sharing - Assign','marketing_hub'),
    ('PRIVILEGE_ACCOUNT_SECURITY_USER_OVERVIEW','Account and security - All the user - Overview','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_USER_EDIT','Account and security - All the user - Edit user profile','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_USER_ADD','Account and security - All the user - Add new','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_USER_DELETE','Account and security - All the user - Delete','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_ACCOUNT_SETTING_OVERVIEW','Account and security - Account setting - Overview','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_ACCOUNT_SETTING_EDIT','Account and security - Account setting - Edit profile','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_SECURITY_OVERVIEW','Account and security - Security - Overview','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_SECURITY_SETFA','Account and security - Security - Set FA','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_SECURITY_CHANGE_PASSWORD','Account and security - Security - Change password','account_security'),
    ('PRIVILEGE_ACCOUNT_SECURITY_ROLE_PERMISSION_OVERVIEW','Account and security - Role and permission - Overview all role','role_and_permission'),
    ('PRIVILEGE_ACCOUNT_SECURITY_ROLE_PERMISSION_EDIT','Account and security - Role and permission - Edit role and permission','role_and_permission');
