server:
  port: 8080

swagger-ui:
  server:
    url: 'http://44.215.182.14:8080'

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER:postgres}
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_management}?useSSL=false
        password: ${DB_PASSWORD:Vuong123}
