server:
  port: 9000

swagger-ui:
  server:
    url: 'http://localhost:9000'

spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        url: jdbc:postgresql://localhost:5433/order_management?useSSL=false
        password: Vuong@123
