server:
  port: 8080

swagger-ui:
  server:
    url: 'http://13.251.17.45:8080'

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        url: jdbc:postgresql://ordermanagement.c4meynty9bqi.ap-southeast-1.rds.amazonaws.com:5432/ordermanagement?useSSL=false
        password: Vuong123

